name: CI/CD Pipeline

on:
  push:
    branches:
      - main
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push Docker image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./app
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/my-flask-app:latest

  deploy-to-minikube:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # SSHを使ってCentOS上のMinikubeに接続し、デプロイを実行します
      - name: Deploy to Minikube via SSH
        run: |  
          # SSH接続に必要なキーをセットアップ
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          
          # SSH経由でMinikubeへデプロイ
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no CentUser10@192.168.56.105 "
            minikube image load ${{ secrets.DOCKER_HUB_USERNAME }}/my-flask-app:latest
            kubectl create secret generic postgres-secret --from-literal=POSTGRES_USER=user --from-literal=POSTGRES_PASSWORD=password --from-literal=POSTGRES_DB=mydatabase
            kubectl apply -f k8s-deployment.yml
          "
